### PR TITLE
Support Stripe and Authnetecheck extensions

### PR DESCRIPTION
**Pull request by mattwire**
@eileenmcnaughton This allows notificationlog to work with other extensions (ie. ones that take a json string directly).

I suggested in mattermost that we add a `class_name_ipn` metadata to `payment_processor_type` that we could use here to get the IPN class name - let me know your thoughts as this would effectively allow this extension to support most payment processors which implement IPNs in a "standard" way.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hmm - this feels like it should possibly be moved to core if it's still growing to more processors. 
I also have this functionality in the Omnipay extension (probably apiv4: PaymentProcessor.retryCallback or something)

What about the main processor class implements a function getCallBack that returns a callable?

**Comment by eileenmcnaughton** [comment]
Actually - I prefer the way Omnipay implements this - with a function on the Payment class   public function processPaymentNotification($params) {

**Comment by guyiac** [comment]
what's the status of this? Does this extension work with the Stripe and Authnet extensions?

**Comment by mattwire** [comment]
@guyiac Actually we can close this. I implemented my own version which you already have installed via mjwshared - https://lab.civicrm.org/extensions/mjwshared/-/blob/master/docs/api.md

**Pull request closed without merging**
